# Generated by Django 5.1.2 on 2024-12-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('performer', 'Performer'), ('judge', 'Judge')], default='performer', max_length=10),
        ),
    ]
